[tool.poetry]
name = "pythonproject1"
version = "0.1.0"
description = ""
authors = ["s.leontev <neonyan15@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
